version: '3'

services:
  namenode:
    image: namenode-image
    container_name: namenode
    networks:
      - hadoop-cluster
    hostname: namenode
    networks:
      - hadoop-cluster
    ports:
      - "9870:9870"
      - "8088:8088"
    cpus: 1
    mem_limit: 3072m
    expose:
      - "8000-10000"
    command: /inicio.sh

  datanode1:
    image: datanode-image
    container_name: datanode1
    networks:
      - hadoop-cluster
    hostname: datanode1
    cpus: 1
    mem_limit: 3072m
    expose:
      - "8000-10000"
      - "50000-50200"
    command: /inicio.sh

  datanode2:
    image: datanode-image
    container_name: datanode2
    networks:
      - hadoop-cluster
    hostname: datanode2
    cpus: 1
    mem_limit: 3072m
    expose:
      - "8000-10000"
      - "50000-50200"
    command: /inicio.sh

  datanode3:
    image: datanode-image
    container_name: datanode3
    networks:
      - hadoop-cluster
    hostname: datanode3
    cpus: 1
    mem_limit: 3072m
    expose:
      - "8000-10000"
      - "50000-50200"
    command: /inicio.sh

  datanode4:
    image: datanode-image
    container_name: datanode4
    networks:
      - hadoop-cluster
    hostname: datanode4
    cpus: 1
    mem_limit: 3072m
    expose:
      - "8000-10000"
      - "50000-50200"
    command: /inicio.sh

networks:
  hadoop-cluster:
